"""
Production ML Training with MLflow Tracking
============================================
Enhanced version of train_with_semantic_production.py with comprehensive tracking.

WHAT THIS DOES:
- Trains 3 models (XGBoost, RandomForest, GradientBoosting)
- Logs ALL hyperparameters to MLflow (enables comparison)
- Logs ALL metrics (test AUC, adversarial accuracy, training time)
- Saves plots (confusion matrix, ROC curve, feature importance)
- Stores models with input/output schema validation

WHY MLFLOW:
- Compare 50+ experiments without manual tracking
- Reproduce any result from months ago (all metadata saved)
- Find best model by sorting: "Which had highest adversarial accuracy?"
- No more lost models: "What hyperparameters did model_v2.pkl use?"

EDUCATIONAL NOTES:
- mlflow.start_run(): Context manager for automatic cleanup
- mlflow.log_param(): Immutable config values (hyperparameters)
- mlflow.log_metric(): Evaluation results (can log multiple times)
- mlflow.log_artifact(): Files (plots, CSVs, models)
- infer_signature(): Auto-detect input/output schema for validation

Author: Ali
Date: December 21, 2024
"""

import sys
from pathlib import Path
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.metrics import (
    classification_report, confusion_matrix, roc_auc_score, 
    roc_curve
)
from sklearn.preprocessing import StandardScaler
import xgboost as xgb
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime

# MLflow imports - NEW ADDITIONS
import mlflow
import mlflow.sklearn
import mlflow.xgboost
from mlflow.models.signature import infer_signature

# Add project source to path (enables imports from src/chainguardian)
sys.path.insert(0, str(Path(__file__).parent.parent.parent / 'src'))

print("\n" + "="*80)
print("🎯 PRODUCTION ML TRAINING WITH MLFLOW TRACKING")
print("="*80)

# ============================================================================
# MLFLOW SETUP
# ============================================================================
# EDUCATIONAL NOTE: Experiments group related runs together
# Think: Experiment = Project, Run = Single training execution
print("\n📊 MLFLOW SETUP")
print("-" * 80)

# Set experiment name (all runs will be grouped under this)
EXPERIMENT_NAME = "smart_contract_vulnerability_detection"
mlflow.set_experiment(EXPERIMENT_NAME)

# Get experiment metadata
experiment = mlflow.get_experiment_by_name(EXPERIMENT_NAME)
print(f"✅ Experiment: {EXPERIMENT_NAME}")
print(f"   ID: {experiment.experiment_id}")
print(f"   Artifact Location: {experiment.artifact_location}")

# EDUCATIONAL NOTE: Tracking URI determines where metadata is stored
# Default: ./mlruns (local filesystem)
# Production: PostgreSQL or MySQL for multi-user access
# For now, we use default (fine for single developer)

# ============================================================================
# STEP 1: LOAD DATA
# ============================================================================
print("\n📊 STEP 1: LOADING DATASET")
print("-" * 80)

# Load complete dataset with all 93 features (85 baseline + 8 semantic)
# EDUCATIONAL NOTE: This CSV was generated by your feature extraction pipeline
# It contains pre-computed features, so we don't need to run Slither again
df = pd.read_csv('data/complete_dataset_with_semantic.csv')
print(f"✅ Loaded {len(df)} contracts with {len(df.columns)} columns")

# Create binary vulnerability labels
# EDUCATIONAL NOTE: We combine multiple data sources into binary classification
# Vulnerable sources: smartbugs_curated, production_vulnerable, trail_of_bits
# Safe sources: openzeppelin, production_safe
df['is_vulnerable'] = df['data_source'].isin([
    'smartbugs_curated',
    'production_vulnerable',
    'trail_of_bits'
]).astype(int)

# Special handling for adversarial test set (hand-labeled)
# EDUCATIONAL NOTE: Adversarial contracts use filename patterns for labels
# because they're custom-designed edge cases, not from standard datasets
adversarial_mask = df['data_source'] == 'adversarial_test'
df.loc[adversarial_mask, 'is_vulnerable'] = df.loc[adversarial_mask, 'contract_name'].str.contains(
    'reentrancy|vulnerable|danger|exploit|honeypot|obvious',
    case=False,
    na=False
).astype(int)

# Print label distribution (check for class imbalance)
print(f"\n📊 Label Distribution:")
print(f"   Vulnerable: {df['is_vulnerable'].sum()} ({df['is_vulnerable'].sum()/len(df)*100:.1f}%)")
print(f"   Safe: {(~df['is_vulnerable'].astype(bool)).sum()} ({(~df['is_vulnerable'].astype(bool)).sum()/len(df)*100:.1f}%)")

print(f"\n📊 By Data Source:")
print(df.groupby('data_source')['is_vulnerable'].agg(['sum', 'count']).to_string())

# ============================================================================
# STEP 2: FEATURE SELECTION
# ============================================================================
print("\n🔧 STEP 2: FEATURE SELECTION")
print("-" * 80)

# EDUCATIONAL NOTE: Feature engineering is CRITICAL for ML performance
# We organize features into logical groups for maintainability
# Each group represents a different aspect of contract security

# Group 1: Vulnerability Flags (23 features)
# WHAT: Binary flags for specific vulnerability types detected by Slither
# WHY: Direct indicators of known vulnerability patterns
vulnerability_flags = [
    'has_reentrancy', 'has_access_control_issues', 'has_timestamp_dependency',
    'has_unchecked_call', 'has_reentrancy_unlimited', 'has_reentrancy_benign',
    'has_reentrancy_events', 'has_unchecked_transfer', 'has_controlled_delegatecall',
    'has_delegatecall_loop', 'has_uninitialized_state', 'has_uninitialized_storage',
    'has_uninitialized_local', 'has_tx_origin', 'has_inline_assembly',
    'has_locked_ether', 'has_msg_value_loop', 'has_shadowing_state',
    'has_shadowing_builtin', 'has_shadowing_abstract', 'has_unused_state_vars',
    'has_unused_return_values', 'has_incorrect_solc_version', 'has_floating_pragma',
    'has_outdated_compiler'
]

# Group 2: Severity Counts (3 features)
# WHAT: Count of high/medium/low severity issues found by Slither
# WHY: Aggregate risk score - more issues = higher risk
severity_counts = [
    'high_severity_count', 'medium_severity_count', 'low_severity_count'
]

# Group 3: AST Features (17 features)
# WHAT: Structural properties from Abstract Syntax Tree analysis
# WHY: Code complexity metrics - complex code = higher risk of bugs
# SOLIDITY ANALOGY: Like measuring contract size, function count, inheritance depth
ast_features = [
    'num_functions', 'num_external_calls', 'num_state_vars', 'num_modifiers',
    'max_cyclomatic_complexity', 'num_low_level_calls', 'lines_of_code',
    'num_contracts_in_file', 'num_dependencies', 'avg_function_complexity',
    'num_functions_high_complexity', 'num_comments', 'comment_to_code_ratio',
    'num_payable_functions', 'num_library_calls', 'inheritance_depth',
    'num_unused_functions'
]

# Group 4: Detector Statistics (9 features)
# WHAT: Metadata about Slither's analysis (how many detectors fired)
# WHY: Higher detector hits = more suspicious patterns found
detector_stats = [
    'high_confidence_detectors', 'medium_confidence_detectors',
    'low_confidence_detectors', 'security_detectors_triggered',
    'optimization_detectors_triggered', 'total_detector_hits',
    'unique_vulnerability_types', 'detectors_per_function', 'detectors_per_loc'
]

# Group 5: Risk Scores (3 features)
# WHAT: Composite risk scores computed from other features
# WHY: Pre-computed risk indicators (weighted combinations)
risk_scores = [
    'risk_score_simple', 'risk_score_weighted', 'is_high_risk'
]

# Group 6: Graph Features (25 features)
# WHAT: Properties from control flow, call graph, data flow analysis
# WHY: Graph structure reveals execution patterns (cycles, depth, connectivity)
# EDUCATIONAL: CFG = Control Flow Graph, CG = Call Graph, DFG = Data Flow Graph
graph_features = [
    # Control Flow Graph (8 features) - execution paths through functions
    'cfg_num_nodes', 'cfg_num_edges', 'cfg_num_cycles', 'cfg_max_depth',
    'cfg_avg_branching', 'cfg_has_complex_loops', 'cfg_num_exit_points',
    'cfg_cyclomatic_total',
    # Call Graph (10 features) - function call relationships
    'cg_num_nodes', 'cg_num_edges', 'cg_max_call_depth', 'cg_num_external_calls',
    'cg_external_call_ratio', 'cg_has_cyclic_calls', 'cg_num_public_entry_points',
    'cg_num_internal_functions', 'cg_avg_calls_per_function', 'cg_num_leaf_functions',
    # Data Flow Graph (7 features) - how data moves through contract
    'dfg_num_state_vars', 'dfg_num_tainted_flows', 'dfg_has_cross_function_flow',
    'dfg_num_sensitive_sinks', 'dfg_num_external_sources', 'dfg_taint_to_sink_ratio',
    'dfg_num_unvalidated_inputs'
]

# Group 7: Semantic Features (8 features) ⭐ INNOVATION
# WHAT: Execution order analysis (CEI pattern violations)
# WHY: Captures semantics that syntax analysis misses
# BREAKTHROUGH: This is YOUR contribution - detects reentrancy via execution order
# SOLIDITY ANALOGY: Checks-Effects-Interactions pattern enforcement
semantic_features = [
    'cei_violations',              # Count of CEI pattern violations
    'cei_safe_functions',          # Count of functions following CEI
    'cei_pattern_score',           # Overall CEI compliance (0-1)
    'has_reentrancy_guard',        # Has nonReentrant modifier
    'functions_with_reentrancy_guard',  # Count of protected functions
    'state_before_call_count',     # State updates BEFORE external calls (safe)
    'state_after_call_count',      # State updates AFTER external calls (DANGER!)
    'unchecked_calls_in_critical_context'  # Unchecked calls in risky contexts
]

# Combine all feature groups
baseline_features = (
    vulnerability_flags + severity_counts + ast_features + 
    detector_stats + risk_scores + graph_features
)
full_features = baseline_features + semantic_features

# Filter to only features that exist in the dataset
# EDUCATIONAL NOTE: This handles cases where feature extraction failed
# Better to exclude missing features than crash with KeyError
baseline_features = [f for f in baseline_features if f in df.columns]
full_features = [f for f in full_features if f in df.columns]
semantic_available = [f for f in semantic_features if f in df.columns]

print(f"✅ Baseline features: {len(baseline_features)}")
print(f"✅ Semantic features: {len(semantic_available)}")
print(f"✅ Total features: {len(full_features)}")

print(f"\n🌟 Semantic features included:")
for feat in semantic_available:
    print(f"   • {feat}")

# ============================================================================
# STEP 3: TRAIN/TEST SPLIT
# ============================================================================
print("\n🔀 STEP 3: TRAIN/TEST SPLIT")
print("-" * 80)

# EDUCATIONAL NOTE: Separate adversarial set for final robustness testing
# Main dataset: 80/20 train/test split (standard practice)
# Adversarial: Held-out 25 contracts (edge cases, not seen during training)
adversarial_df = df[df['data_source'] == 'adversarial_test'].copy()
main_df = df[df['data_source'] != 'adversarial_test'].copy()

print(f"Main dataset: {len(main_df)} contracts")
print(f"Adversarial test: {len(adversarial_df)} contracts")

# Split main dataset
X_main = main_df[full_features]
y_main = main_df['is_vulnerable']

# EDUCATIONAL NOTE: stratify=y_main ensures train/test have same class ratio
# This prevents train=30% vulnerable, test=10% vulnerable (bad!)
X_train, X_test, y_train, y_test = train_test_split(
    X_main, y_main, 
    test_size=0.2,      # 80% train, 20% test (standard split)
    random_state=42,    # Fixed seed for reproducibility
    stratify=y_main     # Maintain class distribution
)

print(f"\n📊 Split:")
print(f"   Training: {len(X_train)} ({y_train.sum()} vulnerable)")
print(f"   Test: {len(X_test)} ({y_test.sum()} vulnerable)")
print(f"   Adversarial: {len(adversarial_df)} ({adversarial_df['is_vulnerable'].sum()} vulnerable)")

# Calculate class weights for imbalanced data
# EDUCATIONAL NOTE: Class weights tell model "mistakes on minority class cost more"
# Formula: n_samples / (n_classes * n_samples_for_class)
# With 213 vulnerable / 750 safe → vulnerable samples weighted 3.5x higher
pos_weight = len(y_train) / (2 * y_train.sum())
neg_weight = len(y_train) / (2 * (len(y_train) - y_train.sum()))

print(f"\n📊 Class weights: Vulnerable={pos_weight:.2f}, Safe={neg_weight:.2f}")

# ============================================================================
# STEP 4: SCALE FEATURES
# ============================================================================
print("\n🔄 STEP 4: SCALING FEATURES")
print("-" * 80)

# EDUCATIONAL NOTE: StandardScaler normalizes features to mean=0, std=1
# WHY: Models like XGBoost work better when features are on similar scales
# Without scaling: "lines_of_code" (range 10-5000) dominates "has_reentrancy" (0 or 1)
# IMPROVEMENT OPPORTUNITY: Use RobustScaler (handles outliers better)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Scale adversarial set (using same scaler fitted on train data)
# EDUCATIONAL NOTE: NEVER fit scaler on test data (causes data leakage!)
if len(adversarial_df) > 0:
    X_adv = adversarial_df[full_features]
    y_adv = adversarial_df['is_vulnerable']
    X_adv_scaled = scaler.transform(X_adv)
else:
    X_adv_scaled = None
    y_adv = None

print(f"✅ Features scaled using StandardScaler")
print(f"   Mean ≈ 0, Std ≈ 1 for all features")

# ============================================================================
# STEP 5: TRAINING FUNCTION WITH MLFLOW
# ============================================================================

def train_and_log_model(
    model_name: str,
    model,
    X_train_scaled,
    y_train,
    X_test_scaled,
    y_test,
    X_adv_scaled=None,
    y_adv=None,
    feature_names=None
):
    """
    Train a model and log everything to MLflow for tracking and comparison.
    
    WHAT THIS FUNCTION DOES:
    1. Starts an MLflow run (groups all logs under one execution)
    2. Logs hyperparameters (enables "what config was this?")
    3. Trains the model (actual ML training)
    4. Logs metrics (test AUC, accuracy, adversarial performance)
    5. Creates visualizations (confusion matrix, ROC curve, feature importance)
    6. Logs model with schema (enables loading later with validation)
    7. Adds searchable tags (enables filtering: "show me production models")
    
    WHY MLFLOW OVER MANUAL TRACKING:
    - Manual: "model_20251220_143052.pkl" → What hyperparameters? Lost forever
    - MLflow: Searchable database → "Show me runs where test_auc > 0.95"
    - Manual: Compare 50 models → Load each, test each (hours)
    - MLflow: UI table → Sort by AUC, click best model (seconds)
    
    PARAMETERS:
        model_name: Human-readable name (e.g., "XGBoost", "RandomForest")
        model: Trained sklearn/xgboost model object
        X_train_scaled: Scaled training features
        y_train: Training labels
        X_test_scaled: Scaled test features
        y_test: Test labels
        X_adv_scaled: Scaled adversarial features (optional)
        y_adv: Adversarial labels (optional)
        feature_names: List of feature names for importance plots
        
    RETURNS:
        tuple: (trained_model, test_auc)
        
    EDUCATIONAL NOTES:
    - with mlflow.start_run(): Auto-closes run even if error occurs
    - mlflow.log_param(): Immutable (can't change once set)
    - mlflow.log_metric(): Mutable (can log same metric multiple times)
    - infer_signature(): Validates inputs/outputs match expected schema
    """
    
    # Start MLflow run with descriptive name
    # EDUCATIONAL NOTE: run_name shows in UI, makes finding specific runs easy
    with mlflow.start_run(run_name=f"{model_name}_{datetime.now().strftime('%Y%m%d_%H%M')}"):
        
        print(f"\n{'='*60}")
        print(f"Training: {model_name}")
        print(f"{'='*60}")
        
        # ----------------------------------------------------------------
        # 1. LOG PARAMETERS (Configuration)
        # ----------------------------------------------------------------
        # EDUCATIONAL NOTE: Parameters are INPUTS to training
        # They're immutable (can't change) and must be simple types
        # WHY: Enables comparison "How does max_depth affect AUC?"
        
        mlflow.log_param("model_type", model_name)
        
        # Extract and log all model hyperparameters
        # EDUCATIONAL NOTE: get_params() returns dict of all hyperparameters
        # We filter to simple types because MLflow can't handle complex objects
        model_params = model.get_params()
        for param, value in model_params.items():
            if isinstance(value, (int, float, str, bool)):
                mlflow.log_param(f"model_{param}", value)
        
        # Log dataset characteristics
        # EDUCATIONAL NOTE: Data properties affect results as much as hyperparameters
        # Logging these enables debugging: "Did class imbalance change?"
        mlflow.log_params({
            "train_size": len(X_train_scaled),
            "test_size": len(X_test_scaled),
            "num_features": len(feature_names) if feature_names else X_train_scaled.shape[1],
            "pos_weight": pos_weight,
            "random_state": 42
        })
        
        # ----------------------------------------------------------------
        # 2. TRAIN MODEL
        # ----------------------------------------------------------------
        print(f"🚀 Training {model_name}...")
        train_start = datetime.now()
        
        # Actual model training (this is where ML happens!)
        model.fit(X_train_scaled, y_train)
        
        train_duration = (datetime.now() - train_start).total_seconds()
        print(f"✅ Training complete in {train_duration:.1f}s")
        
        # Log training time (important for production systems)
        # EDUCATIONAL NOTE: Fast models enable rapid iteration
        # XGBoost at 2s vs Neural Net at 2hr → 3600x faster experimentation!
        mlflow.log_metric("train_duration_seconds", train_duration)
        
        # ----------------------------------------------------------------
        # 3. EVALUATE ON TEST SET
        # ----------------------------------------------------------------
        # EDUCATIONAL NOTE: Test set is unseen during training
        # Performance here estimates real-world performance
        print(f"\n📊 Test Set Evaluation:")
        
        y_pred_test = model.predict(X_test_scaled)
        y_pred_proba_test = model.predict_proba(X_test_scaled)[:, 1]
        
        # Calculate metrics
        test_auc = roc_auc_score(y_test, y_pred_proba_test)
        test_accuracy = (y_pred_test == y_test).sum() / len(y_test)
        
        # Get precision, recall, F1 from classification report
        # EDUCATIONAL NOTE: Precision = "Of predicted vulnerable, how many truly are?"
        #                   Recall = "Of truly vulnerable, how many did we catch?"
        #                   F1 = Harmonic mean of precision and recall
        report = classification_report(y_test, y_pred_test, output_dict=True)
        test_precision = report['1']['precision']
        test_recall = report['1']['recall']
        test_f1 = report['1']['f1-score']
        
        # Log all test metrics to MLflow
        # EDUCATIONAL NOTE: Logging multiple metrics enables multi-objective optimization
        # "Best AUC" ≠ "Best recall" → Choose based on business requirements
        mlflow.log_metrics({
            "test_auc": test_auc,
            "test_accuracy": test_accuracy,
            "test_precision": test_precision,
            "test_recall": test_recall,
            "test_f1": test_f1
        })
        
        print(f"   AUC: {test_auc:.4f}")
        print(f"   Accuracy: {test_accuracy:.4f}")
        print(f"   Precision: {test_precision:.4f}")
        print(f"   Recall: {test_recall:.4f}")
        print(f"   F1: {test_f1:.4f}")
        
        # ----------------------------------------------------------------
        # 4. EVALUATE ON ADVERSARIAL SET (If Available)
        # ----------------------------------------------------------------
        # EDUCATIONAL NOTE: Adversarial test checks robustness to edge cases
        # High test AUC + low adversarial accuracy = model learned dataset artifacts
        if X_adv_scaled is not None and y_adv is not None:
            print(f"\n🎯 Adversarial Set Evaluation:")
            
            y_pred_adv = model.predict(X_adv_scaled)
            adv_accuracy = (y_pred_adv == y_adv).sum() / len(y_adv)
            
            mlflow.log_metric("adversarial_accuracy", adv_accuracy)
            
            print(f"   Accuracy: {adv_accuracy:.4f} ({adv_accuracy:.1%})")
        
        # ----------------------------------------------------------------
        # 5. CREATE AND LOG VISUALIZATIONS
        # ----------------------------------------------------------------
        # EDUCATIONAL NOTE: Plots are saved as "artifacts" in MLflow
        # Artifacts = files associated with a run (models, plots, CSVs, etc.)
        print(f"\n📈 Creating visualizations...")
        
        # 5a. Confusion Matrix
        # EDUCATIONAL NOTE: Shows TN, FP, FN, TP counts
        # Diagonal = correct predictions, off-diagonal = errors
        cm = confusion_matrix(y_test, y_pred_test)
        plt.figure(figsize=(8, 6))
        sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', 
                    xticklabels=['Safe', 'Vulnerable'],
                    yticklabels=['Safe', 'Vulnerable'])
        plt.title(f'Confusion Matrix - {model_name}')
        plt.ylabel('True Label')
        plt.xlabel('Predicted Label')
        plt.tight_layout()
        
        cm_path = f'confusion_matrix_{model_name}.png'
        plt.savefig(cm_path, dpi=150)
        mlflow.log_artifact(cm_path)  # Upload to MLflow
        plt.close()
        
        # 5b. ROC Curve
        # EDUCATIONAL NOTE: ROC shows trade-off between TPR and FPR
        # AUC = area under curve → higher is better
        # Perfect model: AUC = 1.0, Random: AUC = 0.5
        fpr, tpr, thresholds = roc_curve(y_test, y_pred_proba_test)
        plt.figure(figsize=(8, 6))
        plt.plot(fpr, tpr, label=f'{model_name} (AUC = {test_auc:.3f})', linewidth=2)
        plt.plot([0, 1], [0, 1], 'k--', label='Random Classifier')
        plt.xlim([0.0, 1.0])
        plt.ylim([0.0, 1.05])
        plt.xlabel('False Positive Rate')
        plt.ylabel('True Positive Rate')
        plt.title(f'ROC Curve - {model_name}')
        plt.legend(loc="lower right")
        plt.grid(alpha=0.3)
        plt.tight_layout()
        
        roc_path = f'roc_curve_{model_name}.png'
        plt.savefig(roc_path, dpi=150)
        mlflow.log_artifact(roc_path)
        plt.close()
        
        # 5c. Feature Importance (If Available)
        # EDUCATIONAL NOTE: Shows which features matter most GLOBALLY
        # Tree models (RF, XGBoost, GB) have built-in feature importance
        # Linear models don't have this attribute
        if hasattr(model, 'feature_importances_') and feature_names:
            importances = model.feature_importances_
            feature_importance_df = pd.DataFrame({
                'feature': feature_names,
                'importance': importances
            }).sort_values('importance', ascending=False).head(20)
            
            # Plot top 20 features
            plt.figure(figsize=(10, 8))
            plt.barh(range(len(feature_importance_df)), feature_importance_df['importance'])
            plt.yticks(range(len(feature_importance_df)), feature_importance_df['feature'])
            plt.xlabel('Importance')
            plt.title(f'Top 20 Feature Importances - {model_name}')
            plt.gca().invert_yaxis()
            plt.tight_layout()
            
            fi_path = f'feature_importance_{model_name}.png'
            plt.savefig(fi_path, dpi=150)
            mlflow.log_artifact(fi_path)
            plt.close()
            
            # Save as CSV for further analysis
            fi_csv_path = f'feature_importance_{model_name}.csv'
            feature_importance_df.to_csv(fi_csv_path, index=False)
            mlflow.log_artifact(fi_csv_path)
        
        # ----------------------------------------------------------------
        # 6. LOG MODEL
        # ----------------------------------------------------------------
        # EDUCATIONAL NOTE: infer_signature validates inputs/outputs
        # If you later try to predict with wrong number of features → error
        # Better to fail fast than get silent wrong predictions!
        print(f"\n💾 Logging model to MLflow...")
        
        signature = infer_signature(X_train_scaled, y_pred_proba_test)
        
        # Use framework-specific logger for better metadata
        # EDUCATIONAL NOTE: mlflow.xgboost.log_model() saves XGBoost-specific info
        # mlflow.sklearn.log_model() saves sklearn-specific info
        # This enables features like distributed prediction, GPU inference, etc.
        if isinstance(model, xgb.XGBClassifier):
            mlflow.xgboost.log_model(
                model,
                name="XGBClassifier",
                signature=signature
            )
        else:
            mlflow.sklearn.log_model(
                model,
                name="model",
                signature=signature
            )
        
        # ----------------------------------------------------------------
        # 7. LOG TAGS (Metadata for Filtering)
        # ----------------------------------------------------------------
        # EDUCATIONAL NOTE: Tags enable searching/filtering in MLflow UI
        # Example: "Show me all production models by ali"
        # filter_string="tags.stage = 'production' AND tags.developer = 'ali'"
        mlflow.set_tags({
            "developer": "ali",
            "purpose": "production_candidate",
            "stage": "experimental"
        })
        
        print(f"✅ Run logged to MLflow!")
        print(f"   Run ID: {mlflow.active_run().info.run_id}")
        
        return model, test_auc

# ============================================================================
# STEP 6: TRAIN MODELS WITH MLFLOW
# ============================================================================
print("\n🚀 STEP 6: TRAINING MODELS")
print("="*80)

results = {}

# ────────────────────────────────────────────────────────────────────────────
# Model 1: XGBoost (Best Performance)
# ────────────────────────────────────────────────────────────────────────────
# EDUCATIONAL NOTE: XGBoost = Gradient Boosting on steroids
# WHY BEST: Handles tabular data excellently, built-in regularization
# PARAMETERS:
#   n_estimators: Number of trees (more = better fit, but slower)
#   max_depth: Tree depth (higher = more complex, risk overfitting)
#   learning_rate: Step size (lower = more robust, but needs more trees)
#   subsample: % of data per tree (prevents overfitting)
#   scale_pos_weight: Handle class imbalance (weight minority class higher)
print("\n1️⃣  XGBoost Classifier")
xgb_model = xgb.XGBClassifier(
    n_estimators=300,         # 300 trees (good balance)
    max_depth=6,              # Moderate depth (prevents overfitting)
    learning_rate=0.05,       # Conservative learning (robust)
    subsample=0.8,            # Use 80% data per tree
    colsample_bytree=0.8,     # Use 80% features per tree
    scale_pos_weight=pos_weight,  # Handle imbalance
    random_state=42,          # Reproducibility
    eval_metric='logloss'     # Optimize log loss
)

model, auc = train_and_log_model(
    "XGBoost",
    xgb_model,
    X_train_scaled,
    y_train,
    X_test_scaled,
    y_test,
    X_adv_scaled,
    y_adv,
    full_features
)
results['XGBoost'] = {'model': model, 'auc': auc}

# ────────────────────────────────────────────────────────────────────────────
# Model 2: Random Forest (Baseline)
# ────────────────────────────────────────────────────────────────────────────
# EDUCATIONAL NOTE: Random Forest = Ensemble of decision trees
# WHY USEFUL: Simple, interpretable, good baseline
# PARAMETERS:
#   n_estimators: Number of trees (more = better, but diminishing returns)
#   max_depth: Tree depth (15 is deep, allows complex patterns)
#   min_samples_split: Min samples to split node (prevents overfitting)
#   class_weight: Handle imbalance via sample weighting
print("\n\n2️⃣  Random Forest Classifier")
rf_model = RandomForestClassifier(
    n_estimators=300,         # 300 trees
    max_depth=15,             # Deep trees (more expressive)
    min_samples_split=5,      # Need 5 samples to split
    min_samples_leaf=2,       # Min 2 samples per leaf
    class_weight={0: neg_weight, 1: pos_weight},  # Handle imbalance
    random_state=42,
    n_jobs=-1                 # Use all CPU cores
)

model, auc = train_and_log_model(
    "RandomForest",
    rf_model,
    X_train_scaled,
    y_train,
    X_test_scaled,
    y_test,
    X_adv_scaled,
    y_adv,
    full_features
)
results['RandomForest'] = {'model': model, 'auc': auc}

# ────────────────────────────────────────────────────────────────────────────
# Model 3: Gradient Boosting (sklearn Implementation)
# ────────────────────────────────────────────────────────────────────────────
# EDUCATIONAL NOTE: Gradient Boosting = Sequential tree building
# Each tree corrects errors of previous trees
# DIFFERENCE FROM XGBOOST: Sklearn version is simpler, no GPU support
print("\n\n3️⃣  Gradient Boosting Classifier")
gb_model = GradientBoostingClassifier(
    n_estimators=200,         # Fewer trees than XGBoost (slower training)
    max_depth=5,              # Shallower trees
    learning_rate=0.1,        # Higher learning rate (converges faster)
    subsample=0.8,            # Stochastic boosting
    random_state=42
)

model, auc = train_and_log_model(
    "GradientBoosting",
    gb_model,
    X_train_scaled,
    y_train,
    X_test_scaled,
    y_test,
    X_adv_scaled,
    y_adv,
    full_features
)
results['GradientBoosting'] = {'model': model, 'auc': auc}

# ============================================================================
# STEP 7: SUMMARY AND RECOMMENDATIONS
# ============================================================================
print("\n" + "="*80)
print("🎉 TRAINING COMPLETE!")
print("="*80)

# Find best model by AUC
best_model_name = max(results, key=lambda k: results[k]['auc'])
best_auc = results[best_model_name]['auc']

print(f"\n🏆 BEST MODEL: {best_model_name}")
print(f"   Test AUC: {best_auc:.4f}")

print(f"\n📊 All Results (Sorted by AUC):")
for name, result in sorted(results.items(), key=lambda x: x[1]['auc'], reverse=True):
    print(f"   {name:20s}: {result['auc']:.4f}")

print(f"\n🔍 View detailed results in MLflow UI:")
print(f"   URL: http://localhost:5000")
print(f"   Experiment: {EXPERIMENT_NAME}")
print(f"\n💡 Next Steps:")
print(f"   1. Open MLflow UI and compare runs")
print(f"   2. Click on best model to see artifacts")
print(f"   3. Try different hyperparameters (next iteration)")

print("\n" + "="*80 + "\n")